# Channels are checked in the order they are listed.

name: vae-embeddings

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - cudatoolkit
  - imageio
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - scikit-image
  - scikit-learn
  - scipy
  - torchvision
  - tqdm